### ISSUE TITLE
デザインの方向性を決めたい;デザインカンプ(あくまで参考)を作ってみました

### ISSUE THREAD

**Issue by irhdevel** [Ixy194194/Ixy-#45]
# 概要
デザインの具体的な方向性を決めたほうがいいかと思ったのでIssueを立ててみました。
PRででてきたデザインをすべて取り込んで行くのもいいですが、やはりサイトを作るときにはデザインカンプや、方向性を話せる場所があると便利で、サイトにも統一感が出る気がします。

私が方針決定するのは違うでしょうし、皆さんの意見もあると思うので、あくまで参考程度のデザイン案としてですが私も試しに作ってみました、改善案やその他デザイン案があればこのIssueなどでデザインの方向性を決めたりできたら良いなと思います。（勝手にいきなり作って出してごめんなさい。）

方向性を決める必要がなければCloseしてしまっても構いません。

## 参考用に試しに作ってみたもの
![Full HD](https://user-images.githubusercontent.com/121326808/228883244-d8dd87e7-72c0-46a9-9af3-5cfcb6f5a1bf.jpg)

**Comment by irhdevel** [comment]
(SNSへのリンクにアイコンを使うと良さそうですが、ライセンス周りが厳しそう...)

**Comment by itta611** [comment]
その辺のアイコンならいくらでもあると思いますよ...！
（ちなみに僕の推しはtabler iconsです）

**Comment by irhdevel** [comment]
なるほど。tabler icons初めて知りました！
ただでもやっぱり、Twitterとかってロゴを使うのに[こういう](https://about.twitter.com/ja/who-we-are/brand-toolkit)ガイドラインみたいなのがあって面倒くさいので、時間のあるときにちょっとづつ読みながら考えてみたいです。

**Comment by itta611** [comment]
今回の場合はリンクとしてちょこっと使うだけなので、（特にtabler iconsを使う場合などでは）そこまで気にすることもないような気がしますね...

**Comment by irhdevel** [comment]
うーん、それでもやっぱりめんどくさいし、なんだか統一感の問題もあるような気がしてきましたし、一応商標だしでライセンス周り考えるのも難しい上怖いので、私が言いだしたことですがやめておきたいです（怖がりすぎかも）

**Comment by itta611** [comment]
統一感についてはtabler iconsがいい感じにやってくれているので、それに関しても特に心配することもないとは思いますが、めっちゃ真面目〜〜！！

**Comment by irhdevel** [comment]
(逃げてるだけです)
あと、文字の可読性を上げるために文字の下の部分のImageBoardを薄くするのと、個人的にもっと情報量がほしいのでProfileを左に寄せるのは割といい感じだと思うのでそのうちPRを投げようと思います。

このPRを立てることで不自由になってよろしくないかもしれないから閉じたほうが良いかもしれない？

**Comment by Ixy194194** [comment]
すみません　最近チェック遅くなってました！自分としては提案自体すごくうれしいのでうまいところに着地していただければと思います！

**Comment by CookieRamen** [comment]
アイコンのガイドラインについてはあくまで影を勝手につけるなとか、比率を変えて使うなとかなのでリンク先のアイコンとして利用する分にはそこまで神経質に気にする必要はありません。
（Twitter本体が守ってないぐらいなので）

また、ガイドラインを完全に無視したサイトは大手企業でも多数存在しますし、ガイドラインを意図的に破ってTwitterに損害を与えてやろう！という意思でもなければ訴えられることはまずないです。

そのため、アイコンフォントのTwitterロゴであったり、SVGアイコンについては気にせず使って大丈夫です。

**Comment by irhdevel** [comment]
なるほど、そうなんですね。ちょっと考えずに逃げすぎだったかもしれません、参考になりました。
itta611さんの提案でとても良さそうなのでtabler iconsでPRとか出せたら良いなと思います。
~~TwitterはアイコンいまDoge...~~

**Comment by irhdevel** [comment]
> 外部 API を叩かないこと。

とあるので、Google Fontsは使えなさそう...?
今どうやって公開されているかわからないのですが、変換してファイルとして置いて、それを現状の環境で使うってできるんですかね？（ファイルを置いてCSSを弄ってPR投げたら反映されますかね）
できたとして読み込みが遅くなると言われているので色々と問題はあるかもしれないですが、フォントは重要なのでぜひ変えてみたいと思っています。

**Comment by itta611** [comment]
`@next/font` を使うと外部へのリクエストが防げるので、`@next/font` から Google Fonts を読み込むのが良いかもしれません。

**Comment by irhdevel** [comment]
なるほど！
知りませんでした。Nextすごい...
